Add custom item on select field
ESSS/ng-xform pull request #25
Opened 2018-06-29 16:48 UTC by lvoliveira

2018-07-02 20:51 UTC, edetec approved these changes

2018-07-03 11:20 UTC, igortg requested changes

2018-07-03 11:20 UTC, igortg commented on src/ng-xform/fields/select-field.ts
> +  public addTag?: boolean | AddTagObservableFn ;
The name "tag" is somewhat misleading. _SelectField_ shows a list of `options`, why use tag?

I think `addNewOption` would be more meaningful

2018-07-03 11:57 UTC, lvoliveira commented on src/ng-xform/fields/select-field.ts
> +  public addTag?: boolean | AddTagObservableFn ;
The name was because ng-select uses the same, but I will change.

2018-07-03 19:40 UTC, lincrosenbach approved these changes

2018-07-04 13:13 UTC, merged