Fb rfdap 885 format table values
ESSS/ng-xform pull request #40
Opened 2018-10-16 18:31 UTC by lincrosenbach

2018-10-16 18:43 UTC, lvoliveira approved these changes

2018-10-17 11:38 UTC, igortg reviewed
Can you add `formatOptions` on the `MeasureField` sample of README?

2018-10-17 11:38 UTC, igortg commented on src/ng-xform/select-field/select-field.component.spec.ts
> +  it('should render SelectField with searchHandler', () => {
Nice

2018-10-17 11:39 UTC, igortg approved these changes

2018-10-17 13:46 UTC, lincrosenbach commented
Added to README example of MeasureField with formatOptions

2018-10-17 14:25 UTC, edetec requested changes

2018-10-17 14:25 UTC, edetec commented on src/ng-xform/select-field/select-field.component.spec.ts
> +import { of, Observable } from 'rxjs';
Where are you using it?

2018-10-17 16:03 UTC, lincrosenbach commented on src/ng-xform/select-field/select-field.component.spec.ts
> +import { of, Observable } from 'rxjs';
Removed.

2018-10-17 16:06 UTC, edetec approved these changes

2018-10-17 16:25 UTC, merged