fix(xform): fix MeasureField writeValue method for null values
ESSS/ng-xform pull request #42
Opened 2018-11-14 16:29 UTC by lvoliveira

2018-11-19 11:23 UTC, edetec approved these changes

2018-11-20 15:00 UTC, igortg requested changes

2018-11-20 15:00 UTC, igortg commented on src/ng-xform/measure-field/measure-field.component.ts
> +      this.quantity = undefined;
Are you sure this should be `undefined`? `null` seems more adequate

@edetec would know better

2018-11-20 15:17 UTC, edetec approved these changes

2018-11-20 15:17 UTC, edetec commented on src/ng-xform/measure-field/measure-field.component.ts
> +      this.quantity = undefined;
Both will return the same on ` if (this.quantity)`

2018-11-22 18:18 UTC, igortg approved these changes

2018-11-23 12:42 UTC, merged