feat(ng-xforms): onChangeFn parameter added to DynamicField with description on README.md
ESSS/ng-xform pull request #44
Opened 2018-11-28 12:25 UTC by nobreconfrade

2018-11-28 17:25 UTC, lvoliveira commented on src/ng-xform/field-components/base-dynamic-field.component.ts
> +  onChangeFnObservable(): Observable<any> {
What is this method doing?

2018-11-28 19:25 UTC, igortg requested changes

2018-11-28 19:25 UTC, igortg commented on src/ng-xform/field-components/base-dynamic-field.component.ts
> +      this.control.valueChanges.subscribe(val => {
Wouldn't be good practice to unsubscribe on destructor?

2018-11-28 19:25 UTC, igortg commented on demo/src/app/home/home.component.ts
> +  public onchangefnSubject = new Subject<string>();
Using variable type on the var name is not necessary

2018-11-28 19:25 UTC, igortg commented on demo/src/app/home/home.component.ts
> +      new CustomField({
Why using a `CustomField` here? Use a simpler control (SelectField or TextField) so it would be easier to another Dev to see what's the onChangeFn behaviour.

2018-11-29 11:23 UTC, lincrosenbach approved these changes

2018-11-29 11:23 UTC, lincrosenbach commented on src/ng-xform/field-components/base-dynamic-field.component.ts
> +      this.control.valueChanges.subscribe(val => {
Please add a test which uses this onChangeFn.

2018-11-29 12:15 UTC, nobreconfrade commented on demo/src/app/home/home.component.ts
> +      new CustomField({
I used a custom field to set the `[value]='invertedPhraseValue'` on the html, should I use a `patchValue` in this case?

2018-11-29 12:26 UTC, nobreconfrade commented on src/ng-xform/field-components/base-dynamic-field.component.ts
> +      this.control.valueChanges.subscribe(val => {
Changed that with a `Subscription[]` and moved `  private valueChangeSubscription: Subscription;
` inside it as well.

Thanks @edetec for the advice.

2018-11-29 14:31 UTC, nobreconfrade commented on src/ng-xform/field-components/base-dynamic-field.component.ts
> +  onChangeFnObservable(): Observable<any> {
My mistake, this shouldn't be here.

2018-11-30 15:20 UTC, edetec approved these changes

2018-11-30 17:05 UTC, igortg approved these changes

2018-11-30 17:23 UTC, lvoliveira approved these changes

2018-11-30 18:02 UTC, merged