fix(ng-xform): unsubscribing from searchHandlers
ESSS/ng-xform pull request #53
Opened 2019-01-15 10:07 UTC by nobreconfrade

Simple fix to unsubscribe from select-field `searchHandlers` subscriptions.

2019-01-15 11:39 UTC, lvoliveira requested changes

2019-01-15 11:39 UTC, lvoliveira commented on src/ng-xform/select-field/select-field.component.ts
> +          this.field.searchByValueKeyHandler(value).subscribe((val: any) => {
Make this subscription with a switchMap

2019-01-15 16:26 UTC, lvoliveira commented on src/ng-xform/select-field/select-field.component.ts
> +          this.field.searchByValueKeyHandler(value).subscribe((val: any) => {
```suggestion
          this.viewModel.pipe(
      switchMap((value: any) => {
        this.select.writeValue(value);
        this.updateOptionLabel();
        if (this.field.searchByValueKeyHandler) {
          if (value === undefined || value === null) {
            this.updateOptionLabel();
            return of(null);;
          }
          return this.field.searchByValueKeyHandler(value);
        } else {
          return of(null);
        }
      }),
      tap((val: any) => {
        if (val && this.field.searchHandler) {
          const oldValue = this.optionValues;
          this.optionValues = [val];
          this.select.ngOnChanges({ items: new SimpleChange(oldValue, this.optionValues, !this.optionValues)});
        }
        // this.select.writeValue(val);
        // this.updateOptionLabel();
      })

    ).subscribe();
```

2019-01-15 18:01 UTC, nobreconfrade commented on src/ng-xform/select-field/select-field.component.ts
> +          this.field.searchByValueKeyHandler(value).subscribe((val: any) => {
changed

2019-01-15 18:35 UTC, lvoliveira approved these changes

2019-01-18 18:25 UTC, igortg approved these changes

2019-01-28 12:38 UTC, lincrosenbach approved these changes

2019-01-28 12:38 UTC, lincrosenbach commented on src/ng-xform/select-field/select-field.component.ts
> +    }
Well done! :1st_place_medal:

2019-01-28 13:40 UTC, igortg approved these changes

2019-01-28 16:04 UTC, merged